"use strict";

// Built-in list of common chains operating in the Czech Republic.
// `q` is the search token used when querying OpenStreetMap (kept free of
// special regex characters); it defaults to `name` when omitted.
// Feel free to extend this list — it's just plain data, no other code
// needs to change.
const BRANDS = [
  { id: 1, name: "Albert" },
  { id: 2, name: "Kaufland" },
  { id: 3, name: "Lidl" },
  { id: 4, name: "Billa" },
  { id: 5, name: "Penny Market", q: "Penny" },
  { id: 6, name: "Tesco" },
  { id: 7, name: "Globus" },
  { id: 8, name: "Coop" },
  { id: 9, name: "Norma" },
  { id: 10, name: "dm drogerie markt", q: "dm" },
  { id: 11, name: "Rossmann" },
  { id: 12, name: "Teta drogerie", q: "Teta" },
  { id: 13, name: "OMV" },
  { id: 14, name: "Shell" },
  { id: 15, name: "MOL" },
  { id: 16, name: "Orlen" },
  { id: 17, name: "EuroOil" },
  { id: 18, name: "Benzina" },
  { id: 19, name: "Pap Oil" },
  { id: 21, name: "McDonald's", q: "McDonald" },
  { id: 22, name: "KFC" },
  { id: 23, name: "Burger King" },
  { id: 24, name: "Starbucks" },
  { id: 25, name: "Costa Coffee", q: "Costa" },
  { id: 26, name: "IKEA" },
  { id: 27, name: "Decathlon" },
  { id: 28, name: "Sportisimo" },
  { id: 29, name: "CCC" },
  { id: 30, name: "Deichmann" },
  { id: 31, name: "Humanic" },
  { id: 32, name: "Super Zoo" },
  { id: 34, name: "Alza" },
  { id: 35, name: "Electroworld", q: "Electro World" },
  { id: 36, name: "OBI" },
  { id: 37, name: "Hornbach" },
  { id: 38, name: "Bauhaus" },
  { id: 39, name: "Mountfield" },
  { id: 40, name: "JYSK" },
  { id: 41, name: "Sconto nábytek", q: "Sconto" },
  { id: 42, name: "H&M", q: "H M" },
  { id: 43, name: "C&A", q: "C A" },
  { id: 44, name: "Reserved" },
  { id: 45, name: "Pepco" },
  { id: 46, name: "KiK" },
  { id: 47, name: "Action" },
  { id: 48, name: "Notino" },
  { id: 49, name: "Sephora" },
  { id: 50, name: "Marionnaud" },
  { id: 51, name: "Kiabi" },
  { id: 52, name: "Zoot" },
  { id: 53, name: "Datart" },
  { id: 54, name: "Mall.cz Výdejna", q: "Mall" },
];
